# Generated by Django 4.0.6 on 2022-09-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='Team',
        ),
    ]
