# Generated by Django 4.0.6 on 2023-10-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='test_field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
